all:
	(cd astro && make)
	(cd banner && make)
	(cd fortune && make)
	(cd freq && make)
	(cd lib9 && make)
	(cd libbio && make)
	(cd locale && make)
	(cd ls && make)
	(cd nbperf && make)
	(cd news && make)
	(cd pbd && make)
	(cd primes && make)
	(cd rs && make)
	(cd unicode && make)
	(cd units && make)
	(cd unutf && make)

clean:
	(cd astro && make clean)
	(cd banner && make clean)
	(cd fortune && make clean)
	(cd freq && make clean)
	(cd lib9 && make clean)
	(cd libbio && make clean)
	(cd locale && make clean)
	(cd ls && make clean)
	(cd nbperf && make clean)
	(cd news && make clean)
	(cd pbd && make clean)
	(cd primes && make clean)
	(cd rs && make clean)
	(cd unicode && make clean)
	(cd units && make clean)
	(cd unutf && make clean)
