#	$OpenBSD: Makefile,v 1.4 1997/02/09 13:52:40 deraadt Exp $
#	$NetBSD: Makefile,v 1.5 1995/03/23 08:28:44 cgd Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

all:
	${CC} -I../../libcobalt -lcobalt strfile.c -o strfile

clean:
	rm -fv strfile

install:
