LIB=	openbsd
SHLIB_MAJOR=0
SHLIB_MINOR=0

CFLAGS += -I.

SRCS =	pledge.c \
	getprogname.c \
	strtonum.c \
	pwcache.c \
	setmode.c \
	warnc.c \
	vwarnc.c \
	fts.c \
	malloc.c \
	errc.c \
	verrc.c \
	logwtmp.c \
	getbsize.c \
	fmt_scaled.c \
	ohash.c \
	vis.c \
	unvis.c \
	strmode.c \
	base64.c \
	siphash.c \
	radixsort.c \
	icdb.c \
	md5.c \
	rmd160.c \
	sha1.c \
	sha2.c

.include <bsd.lib.mk>
.include <bsd.subdir.mk>
#TODO: man pages
